### ISSUE TITLE
Doesn't support non-ascii symbols

### ISSUE THREAD

**Issue by Magomogo** [tdecaluwe/node-edifact#8]
This is because of regular expressions like `/[A-Z0-9.,\-()/= ]*/g` used in the Validator. Any advices how to solve this?

**Comment by tdecaluwe** [comment]
I'm aware of this limitation, however I'm currently doing a large refactor of the code base, including support for different character sets (UNOA, ONOB among others). You can find this work on the `syntax-support` branch right now.

**Comment by tdecaluwe** [comment]
What character sets are you using?

**Comment by Magomogo** [comment]
I've tried both iso8859 and UTF.

**Comment by tdecaluwe** [comment]
I merged basic support for this on the `development` branch. The parser now exposes an `encoding(string)` method which accepts an UN/EDIFACT encoding string. Right now this can be any of UNOA, UNOB, UNOC and UNOY.

For latin script (ISO/IEC 8859-1), you'd need to do:

``` javascript
parser.encoding('UNOC');
```

To use unicode you need UNOY. The other latin scripts also require an encoding translation because they aren't unicode subset, which is what node internally uses. As such I didn't support those yet.

All this is included in the latest npm package. Feel free to test!

**Comment by Magomogo** [comment]
Great work, thanks!

**Comment by timkuijsten** [comment]
Shouldn't this be automatically inferred from the UNB segment? (genuine question, I'm new to EDIFACT).

**Comment by tdecaluwe** [comment]
Yes it should. I was working on this, that's why I didn't close the issue yet. The parser starts in a special 'start of message' state which extracts the separators from the UNA segment if there is one. This is where this functionality should be added.

**Comment by RovoMe** [comment]
What's the status of this issue? Currently, version (1.2.8) fetched via `npm install edifact` does not respect `UNOC` defined in the `UNB` segment while declaring `parser.encoding("UNOC");` before parsing the document works. This unfortunately requires to know upfront what encoding the document defines which could be done with looking up the value via RegEx or other means, which might slow down the whole processing a bit.

**Comment by tdecaluwe** [comment]
@RovoMe I'm going to close this issue as of 356b69533d13355b6fbf2a3ebbeb07f8d8bf837a. Automatic detecion of the encoding from the `ÙNB` segment is now supported through the `Reader` class:

```javascript
let reader = new Reader({ autoDetectEncoding: true });
let result = reader.parse(document);
```

The `parse()` method returns an array of segments. Each segment is an object containing a segment `name` and the list of `elements` as an array of arrays with the actual component data.

**Comment by tdecaluwe** [comment]
@RovoMe I'm going to close this issue as of 356b69533d13355b6fbf2a3ebbeb07f8d8bf837a. Automatic detecion of the encoding from the `ÙNB` segment is now supported through the `Reader` class:

```javascript
let reader = new Reader({ autoDetectEncoding: true });
let result = reader.parse(document);
```

The `parse()` method returns an array of segments. Each segment is an object containing a segment `name` and the list of `elements` as an array of arrays with the actual component data.
