### ISSUE TITLE
Doesn't respect release character

### ISSUE THREAD

**Issue by Magomogo** [tdecaluwe/node-edifact#9]
Quote from the documentation:

> Question mark "?" - release character
>   ?  immediately preceding one of the characters ' + : ?   restores their normal meaning.
>  E.g. 10?+10=20 means 10+10=20. Question mark is represented by ??.

**Comment by tdecaluwe** [comment]
Duplicate of #5. This will be resolved in upcoming release as well.

**Comment by tdecaluwe** [comment]
Duplicate of #5. This will be resolved in upcoming release as well.

**Comment by Magomogo** [comment]
Thanks for your work.

How deep are you in the refactoring? When to expect new release?

**Comment by tdecaluwe** [comment]
I'm currently moving all the pieces into the right place, for example splitting out character set handling to a separate class. Afterwards the API will need updating to provide access to the new functionalities, and some smaller patches will have to be made (like the release character support). I'd say somewhere next week to get it on npm.
